# Generated by Django 2.2.5 on 2019-10-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exit_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exitorder',
            old_name='buiilding',
            new_name='building',
        ),
    ]
