# Generated by Django 2.2.5 on 2020-01-08 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_order', '0002_auto_20191005_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitorder',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
    ]
