# Generated by Django 2.2.5 on 2020-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_order', '0003_auto_20200108_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitorder',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
