# Generated by Django 2.2.5 on 2020-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_order', '0004_exitorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitorderproduct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
