# Generated by Django 2.2.5 on 2020-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_order', '0005_auto_20200304_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitorder',
            name='order_pdf',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
