# Generated by Django 2.2.5 on 2020-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_order', '0008_auto_20200309_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitorder',
            name='parcial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitorderproduct',
            name='parcial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitorderproduct',
            name='parcial_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
