# Generated by Django 2.2.5 on 2020-02-13 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_stock', '0001_initial'),
        ('building_work', '0004_buildingwork_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_cost_subtotal', models.FloatField(default=0.0)),
                ('work_price_subtotal', models.FloatField(default=0.0)),
                ('sale_price_subtotal', models.FloatField(default=0.0)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building_work.BuildingWork')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('product_unit_cost', models.FloatField(default=0.0)),
                ('product_cost', models.FloatField(default=0.0)),
                ('work_unit_price', models.FloatField(default=0.0)),
                ('work_price', models.FloatField(default=0.0)),
                ('sale_unit_price', models.FloatField(default=0.0)),
                ('sale_price', models.FloatField(default=0.0)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_stock.ProductStock')),
            ],
            options={
                'db_table': 'budget_products',
            },
        ),
    ]
