# Generated by Django 2.2.5 on 2020-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='actual_budget_subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
