# Generated by Django 2.2.5 on 2020-05-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_actual_budget_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='global_percentage_product_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budget',
            name='global_percentage_work_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='BudgetConceptProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
            options={
                'db_table': 'budget_concepts',
            },
        ),
        migrations.AddField(
            model_name='budgetproducts',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetConceptProduct'),
        ),
    ]
