# Generated by Django 2.2.5 on 2020-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200514_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetproducts',
            name='percentage_sale_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budgetproducts',
            name='percentage_work_price',
            field=models.FloatField(default=0.0),
        ),
    ]
