# Generated by Django 2.2.5 on 2020-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200514_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='final_price_subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
