# Generated by Django 2.2.3 on 2019-07-30 06:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building_work', '0003_auto_20190729_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_addres', models.CharField(max_length=250)),
                ('provider_phone', models.CharField(max_length=10)),
                ('total_price', models.FloatField(default=0.0)),
                ('note', models.CharField(max_length=500)),
                ('buiilding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building_work.BuildingWork')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('deliver_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliver_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='PruchaseOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.PurchaseOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'pruchase_order_products',
            },
        ),
    ]
