# Generated by Django 2.2.5 on 2019-10-14 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_auto_20191014_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
