# Generated by Django 2.2.5 on 2019-10-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_auto_20191014_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
