# Generated by Django 2.2.5 on 2019-10-14 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_auto_20191014_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
