# Generated by Django 2.2.5 on 2020-01-08 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_auto_20191014_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
    ]
