# Generated by Django 2.2.5 on 2020-01-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_status'),
        ('purchase_order', '0008_auto_20200108_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='provider_addres',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='provider_phone',
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
