# Generated by Django 2.2.5 on 2020-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_auto_20200110_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
