# Generated by Django 2.2.5 on 2020-03-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0010_purchaseorderproduct_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
