# Generated by Django 2.2.5 on 2020-03-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0012_purchaseorder_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_pdf',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
