# Generated by Django 2.2.4 on 2019-08-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0003_auto_20190818_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.FloatField(default=0.0)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tool')),
            ],
            options={
                'db_table': 'tool_stock',
            },
        ),
    ]
