# Generated by Django 2.2.3 on 2019-07-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_work', '0002_buildingwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwork',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
