# Generated by Django 2.2.5 on 2020-07-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_stock', '0002_productstock_min_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrebuildBudgetConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prebuild_budget_concepts',
            },
        ),
        migrations.CreateModel(
            name='PrebuildBudgetProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('product_unit_cost', models.FloatField(default=0.0)),
                ('product_cost', models.FloatField(default=0.0)),
                ('work_unit_price', models.FloatField(default=0.0)),
                ('percentage_work_price', models.FloatField(default=0.0)),
                ('work_price', models.FloatField(default=0.0)),
                ('sale_unit_price', models.FloatField(default=0.0)),
                ('percentage_sale_price', models.FloatField(default=0.0)),
                ('sale_price', models.FloatField(default=0.0)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prebuild_concepts.PrebuildBudgetConcept')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_stock.ProductStock')),
            ],
            options={
                'db_table': 'prebuild_budget_products',
            },
        ),
    ]
