# Generated by Django 2.2.3 on 2019-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='administrator', max_length=50),
            preserve_default=False,
        ),
    ]
