# Generated by Django 2.2.5 on 2020-01-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=256, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre contacto')),
                ('contact_phone', models.CharField(max_length=10, verbose_name='Telefono contacto')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
