# Generated by Django 2.2.5 on 2020-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
