# Generated by Django 2.2.5 on 2020-06-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contact_email',
            field=models.CharField(default='', max_length=256, verbose_name='Correo proveedor'),
            preserve_default=False,
        ),
    ]
