# Generated by Django 2.2.5 on 2020-06-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_provider_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.CharField(default='', max_length=30, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
