# Generated by Django 2.2.4 on 2019-08-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building_work', '0004_buildingwork_user'),
        ('tools', '0003_auto_20190818_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(max_length=300, null=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building_work.BuildingWork')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tools_lend',
            },
        ),
    ]
