# Generated by Django 2.2.4 on 2019-08-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20190818_2200'),
        ('tool_lend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toollend',
            name='tool',
        ),
        migrations.CreateModel(
            name='ToolLendbridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('lend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool_lend.ToolLend')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Tool')),
            ],
            options={
                'db_table': 'tool_lend_quantity',
            },
        ),
    ]
