# Generated by Django 2.2.4 on 2019-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_lend', '0002_auto_20190827_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollend',
            name='lend_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='toollend',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
