# Generated by Django 2.2.5 on 2020-01-08 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_lend', '0003_auto_20190829_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollend',
            name='lend_date',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
