# Generated by Django 2.2.5 on 2020-06-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_lend', '0004_auto_20200108_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='toollend',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toollendbridge',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
