# Generated by Django 2.2.5 on 2020-06-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_lend', '0005_auto_20200627_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollend',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
