# Generated by Django 2.2.5 on 2020-07-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_lend', '0006_auto_20200627_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toollend',
            options={'ordering': ['-lend_date']},
        ),
    ]
