# Generated by Django 2.2.3 on 2019-07-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tool_category',
            },
        ),
    ]
