# Generated by Django 2.2.5 on 2020-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='min_stock',
            field=models.FloatField(default=0.0),
        ),
    ]
