# Generated by Django 2.2.3 on 2019-07-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
