# Generated by Django 2.2.3 on 2019-07-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('measure', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_category.ToolCategory')),
            ],
            options={
                'db_table': 'tools',
            },
        ),
    ]
