# Generated by Django 2.2.3 on 2019-07-28 11:43

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='picture',
            field=models.ImageField(blank=True, upload_to=tools.models.tool_image),
        ),
    ]
