# Generated by Django 2.2.4 on 2019-08-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='measure',
        ),
        migrations.AddField(
            model_name='tool',
            name='brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='model',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
