# Generated by Django 2.2.3 on 2019-07-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('measure', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
